spring:
  datasource:
    url: jdbc:h2:file:./data/glimtdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
messenger:
  verify-token: ${MESSENGER_VERIFY_TOKEN}
  page-token: ${MESSENGER_PAGE_TOKEN}
apiBaseUrl: ${API_BASE_URL:http://localhost:8081}