spring:
  datasource:
    url: jdbc:h2:file:./data/glimtdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
messenger:
  verify-token: babyhauge
  page-token: EACJSLXkhNScBO84ooSaMmZBtpRrqWzvGfPfxCwnHwf2rDkDwtAqWaz5I6aLwSw0aQJhbTEQOH5x0QOZBfcZC9uzpr8ZA7DEKDY1EPujfW4g3ZBclfxmTyR6C75tJXEErDYAHGpWE3QWdZA1KYSEejjO8zLwC3dHjIr5O51M5BIhxSKWcBvKN4nsZAVVHOAmZCBmuxoAZD